export type AiCatalogKind = 'agent' | 'creative-plan' | 'video-model' | 'music-model' | 'world-model';

export interface AiCatalogItem {
  kind: AiCatalogKind;
  name: string;
  provider: string;
  providerSlug?: string;
  status: 'available' | 'waitlist' | 'preview' | 'research' | 'announced';
  pricing: string;
  unit: string;
  capabilities: string[];
  bestFor: string;
  url?: string;
}

/**
 * Curated milestone catalog for the new vertical surfaces.
 *
 * These entries are intentionally conservative: public-facing product names,
 * public status labels, and pricing-unit descriptions rather than exact prices.
 * Exact plan prices and scraped allowances will move into plans / usage_prices
 * after each vendor is verified. This lets the product ship with useful category
 * pages today without pretending that every creative or world-model unit is a
 * token price.
 */
export const AI_VERTICAL_CATALOG: AiCatalogItem[] = [
  // Agent / coding-agent plans
  {
    kind: 'agent',
    name: 'Devin',
    provider: 'Cognition',
    status: 'available',
    pricing: 'Subscription / task capacity',
    unit: 'seat, task, compute',
    capabilities: ['autonomous coding', 'browser', 'shell', 'pull requests'],
    bestFor: 'Delegating end-to-end software tasks to a long-running agent.',
  },
  {
    kind: 'agent',
    name: 'Claude Code',
    provider: 'Anthropic',
    providerSlug: 'anthropic',
    status: 'available',
    pricing: 'Bundled with paid Claude tiers / usage limits',
    unit: 'messages, prompts, subscription',
    capabilities: ['CLI', 'repo context', 'terminal', 'tool use'],
    bestFor: 'Repo-aware coding from a terminal workflow.',
  },
  {
    kind: 'agent',
    name: 'OpenAI Codex',
    provider: 'OpenAI',
    providerSlug: 'openai',
    status: 'available',
    pricing: 'Bundled with paid ChatGPT tiers',
    unit: 'subscription, tasks',
    capabilities: ['coding agent', 'repo tasks', 'ChatGPT integration'],
    bestFor: 'Coding tasks inside the OpenAI / ChatGPT ecosystem.',
  },
  {
    kind: 'agent',
    name: 'Replit Agent',
    provider: 'Replit',
    status: 'available',
    pricing: 'Subscription / usage credits',
    unit: 'credits, seat',
    capabilities: ['app generation', 'deployments', 'database', 'hosting'],
    bestFor: 'Building and deploying small apps in one workspace.',
  },
  {
    kind: 'agent',
    name: 'Manus',
    provider: 'Manus',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, tasks',
    capabilities: ['browser', 'files', 'research', 'long tasks'],
    bestFor: 'General web and research tasks with file outputs.',
  },
  {
    kind: 'agent',
    name: 'Genspark AI Agent',
    provider: 'Genspark',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, tasks',
    capabilities: ['research', 'browser', 'presentations', 'documents'],
    bestFor: 'Research and content tasks that need browsed sources.',
  },
  {
    kind: 'agent',
    name: 'GitHub Copilot Coding Agent',
    provider: 'GitHub',
    status: 'available',
    pricing: 'Copilot subscription / enterprise controls',
    unit: 'seat, requests',
    capabilities: ['GitHub issues', 'pull requests', 'repo context'],
    bestFor: 'Teams that already live in GitHub pull requests.',
  },
  {
    kind: 'agent',
    name: 'Cursor Background Agents',
    provider: 'Cursor',
    status: 'available',
    pricing: 'Subscription / usage pool',
    unit: 'requests, credits, seat',
    capabilities: ['IDE', 'repo context', 'background tasks'],
    bestFor: 'Developers using Cursor as their primary editor.',
  },
  {
    kind: 'agent',
    name: 'Windsurf / Cascade',
    provider: 'Cognition',
    status: 'available',
    pricing: 'Subscription / usage pool',
    unit: 'credits, requests, seat',
    capabilities: ['IDE', 'agentic coding', 'repo edits'],
    bestFor: 'Agentic coding inside a dedicated AI IDE.',
  },
  {
    kind: 'agent',
    name: 'Lovable',
    provider: 'Lovable',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, projects',
    capabilities: ['app generation', 'frontend', 'Supabase integration'],
    bestFor: 'Shipping web app prototypes quickly from prompts.',
  },

  // Creative plans
  {
    kind: 'creative-plan',
    name: 'Runway Plans',
    provider: 'Runway',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, seconds',
    capabilities: ['video generation', 'image-to-video', 'editing', 'teams'],
    bestFor: 'Professional video generation workflows.',
  },
  {
    kind: 'creative-plan',
    name: 'Kling AI Plans',
    provider: 'Kuaishou',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, generations',
    capabilities: ['text-to-video', 'image-to-video', 'camera control'],
    bestFor: 'High-quality video generation with China/global access split.',
  },
  {
    kind: 'creative-plan',
    name: 'Pika Plans',
    provider: 'Pika',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, generations',
    capabilities: ['video generation', 'effects', 'editing'],
    bestFor: 'Short social video and effect-heavy clips.',
  },
  {
    kind: 'creative-plan',
    name: 'Luma Dream Machine Plans',
    provider: 'Luma AI',
    status: 'available',
    pricing: 'Subscription / generations',
    unit: 'generations, credits',
    capabilities: ['video generation', 'image-to-video', 'Ray models'],
    bestFor: 'Cinematic video generation and creative iteration.',
  },
  {
    kind: 'creative-plan',
    name: 'Suno Plans',
    provider: 'Suno',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, songs',
    capabilities: ['music generation', 'vocals', 'commercial rights'],
    bestFor: 'Generating publishable songs with vocals.',
  },
  {
    kind: 'creative-plan',
    name: 'Udio Plans',
    provider: 'Udio',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, songs',
    capabilities: ['music generation', 'extension', 'downloads'],
    bestFor: 'Music generation with editing and extension workflows.',
  },
  {
    kind: 'creative-plan',
    name: 'Midjourney Plans',
    provider: 'Midjourney',
    status: 'available',
    pricing: 'Subscription / GPU time',
    unit: 'fast hours, relax mode',
    capabilities: ['image generation', 'style control', 'private generation'],
    bestFor: 'High-quality image generation and art direction.',
  },
  {
    kind: 'creative-plan',
    name: 'Ideogram Plans',
    provider: 'Ideogram',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, generations',
    capabilities: ['image generation', 'text rendering', 'editing'],
    bestFor: 'Images that need reliable text rendering.',
  },
  {
    kind: 'creative-plan',
    name: 'Krea Plans',
    provider: 'Krea',
    status: 'available',
    pricing: 'Subscription / credits',
    unit: 'credits, generations',
    capabilities: ['image generation', 'video', 'enhance', 'realtime'],
    bestFor: 'Design workflows that mix image, video and enhancement.',
  },
  {
    kind: 'creative-plan',
    name: 'ElevenLabs Plans',
    provider: 'ElevenLabs',
    status: 'available',
    pricing: 'Subscription / character or minute quotas',
    unit: 'characters, minutes',
    capabilities: ['voice', 'speech', 'music', 'dubbing'],
    bestFor: 'Voice, dubbing and audio production workflows.',
  },

  // Video models
  {
    kind: 'video-model',
    name: 'Sora',
    provider: 'OpenAI',
    providerSlug: 'openai',
    status: 'available',
    pricing: 'ChatGPT plan allowance / future API',
    unit: 'generations, seconds',
    capabilities: ['text-to-video', 'image-to-video', 'storyboard'],
    bestFor: 'OpenAI-native video generation and ChatGPT workflows.',
  },
  {
    kind: 'video-model',
    name: 'Veo',
    provider: 'Google',
    providerSlug: 'google',
    status: 'available',
    pricing: 'Gemini / Vertex AI access',
    unit: 'generations, seconds',
    capabilities: ['text-to-video', 'image-to-video', 'camera control'],
    bestFor: 'Google ecosystem video generation and API workflows.',
  },
  {
    kind: 'video-model',
    name: 'Kling',
    provider: 'Kuaishou',
    status: 'available',
    pricing: 'Credits / subscription',
    unit: 'credits, generations',
    capabilities: ['text-to-video', 'image-to-video', 'motion control'],
    bestFor: 'High-quality clips with strong motion and character control.',
  },
  {
    kind: 'video-model',
    name: 'Runway Gen-4',
    provider: 'Runway',
    status: 'available',
    pricing: 'Credits / subscription',
    unit: 'credits, seconds',
    capabilities: ['video generation', 'editing', 'reference control'],
    bestFor: 'Professional creative teams and video iteration.',
  },
  {
    kind: 'video-model',
    name: 'Pika',
    provider: 'Pika',
    status: 'available',
    pricing: 'Credits / subscription',
    unit: 'credits, generations',
    capabilities: ['video generation', 'effects', 'image-to-video'],
    bestFor: 'Short clips, effects and social formats.',
  },
  {
    kind: 'video-model',
    name: 'Luma Ray',
    provider: 'Luma AI',
    status: 'available',
    pricing: 'Generations / subscription',
    unit: 'generations, credits',
    capabilities: ['video generation', 'cinematic motion', 'image-to-video'],
    bestFor: 'Cinematic outputs and fast creative iteration.',
  },
  {
    kind: 'video-model',
    name: 'Hailuo Video',
    provider: 'MiniMax',
    providerSlug: 'minimax-china',
    status: 'available',
    pricing: 'Credits / subscription',
    unit: 'credits, generations',
    capabilities: ['text-to-video', 'image-to-video', 'China access'],
    bestFor: 'China-accessible video generation workflows.',
  },
  {
    kind: 'video-model',
    name: 'Seedance',
    provider: 'ByteDance / Volcano Engine',
    status: 'available',
    pricing: 'API / platform pricing',
    unit: 'seconds, generations',
    capabilities: ['video generation', 'API', 'China access'],
    bestFor: 'Developer and enterprise video generation in ByteDance ecosystem.',
  },
  {
    kind: 'video-model',
    name: 'Wan / Tongyi Wanxiang Video',
    provider: 'Alibaba',
    providerSlug: 'qwen',
    status: 'available',
    pricing: 'API / platform pricing',
    unit: 'seconds, generations',
    capabilities: ['text-to-video', 'image-to-video', 'China access'],
    bestFor: 'Alibaba Cloud and China-accessible video generation.',
  },
  {
    kind: 'video-model',
    name: 'Vidu',
    provider: 'ShengShu',
    status: 'available',
    pricing: 'Credits / subscription',
    unit: 'credits, generations',
    capabilities: ['video generation', 'image-to-video', 'character consistency'],
    bestFor: 'Video generation with character and reference control.',
  },

  // Music / audio models
  {
    kind: 'music-model',
    name: 'Suno',
    provider: 'Suno',
    status: 'available',
    pricing: 'Credits / subscription',
    unit: 'credits, songs',
    capabilities: ['music generation', 'vocals', 'lyrics'],
    bestFor: 'Complete song generation with vocals.',
  },
  {
    kind: 'music-model',
    name: 'Udio',
    provider: 'Udio',
    status: 'available',
    pricing: 'Credits / subscription',
    unit: 'credits, songs',
    capabilities: ['music generation', 'extend', 'remix'],
    bestFor: 'Music generation with editing and extension.',
  },
  {
    kind: 'music-model',
    name: 'ElevenLabs Music',
    provider: 'ElevenLabs',
    status: 'preview',
    pricing: 'Plan allowance / audio minutes',
    unit: 'minutes, generations',
    capabilities: ['music', 'voice', 'audio production'],
    bestFor: 'Audio workflows that combine music, voice and dubbing.',
  },
  {
    kind: 'music-model',
    name: 'Stable Audio',
    provider: 'Stability AI',
    status: 'available',
    pricing: 'Subscription / API',
    unit: 'seconds, generations',
    capabilities: ['music', 'sound effects', 'API'],
    bestFor: 'Music and sound effects for apps and media.',
  },
  {
    kind: 'music-model',
    name: 'MiniMax Audio',
    provider: 'MiniMax',
    providerSlug: 'minimax-china',
    status: 'available',
    pricing: 'API / platform pricing',
    unit: 'characters, minutes, generations',
    capabilities: ['speech', 'voice', 'audio'],
    bestFor: 'China-accessible audio and voice generation.',
  },
  {
    kind: 'music-model',
    name: 'Seed Audio',
    provider: 'ByteDance',
    status: 'preview',
    pricing: 'Platform / API access',
    unit: 'minutes, generations',
    capabilities: ['audio generation', 'speech', 'music research'],
    bestFor: 'ByteDance ecosystem audio generation and research tracking.',
  },
  {
    kind: 'music-model',
    name: 'Google MusicFX / Lyria',
    provider: 'Google DeepMind',
    providerSlug: 'google',
    status: 'preview',
    pricing: 'Product / partner access',
    unit: 'generations, minutes',
    capabilities: ['music generation', 'research', 'artist tools'],
    bestFor: 'Tracking Google music-generation capabilities as they productize.',
  },
  {
    kind: 'music-model',
    name: 'Meta MusicGen',
    provider: 'Meta',
    status: 'research',
    pricing: 'Open research / self-hosting',
    unit: 'compute',
    capabilities: ['music generation', 'open weights', 'research'],
    bestFor: 'Open model research and self-hosted experimentation.',
  },

  // World models
  {
    kind: 'world-model',
    name: 'Genie / Genie 2',
    provider: 'Google DeepMind',
    providerSlug: 'google',
    status: 'research',
    pricing: 'Research preview',
    unit: 'availability',
    capabilities: ['interactive worlds', 'prompt-to-environment', 'control'],
    bestFor: 'Tracking interactive world generation research.',
  },
  {
    kind: 'world-model',
    name: 'Cosmos',
    provider: 'NVIDIA',
    status: 'preview',
    pricing: 'Developer / platform access',
    unit: 'compute, API',
    capabilities: ['robotics', 'simulation', 'physical AI'],
    bestFor: 'Robotics and physical-world simulation workflows.',
  },
  {
    kind: 'world-model',
    name: 'World Labs',
    provider: 'World Labs',
    status: 'preview',
    pricing: 'Product preview',
    unit: 'availability',
    capabilities: ['3D worlds', 'scene generation', 'spatial intelligence'],
    bestFor: '3D world generation and spatial AI tracking.',
  },
  {
    kind: 'world-model',
    name: 'JEPA-style world models',
    provider: 'Meta / research',
    status: 'research',
    pricing: 'Research',
    unit: 'availability',
    capabilities: ['representation learning', 'planning', 'world modeling'],
    bestFor: 'Research tracking rather than buyer comparison.',
  },
  {
    kind: 'world-model',
    name: 'GameNGen-style game worlds',
    provider: 'Research',
    status: 'research',
    pricing: 'Research',
    unit: 'availability',
    capabilities: ['game simulation', 'interactive video', 'world state'],
    bestFor: 'Tracking neural game and interactive environment generation.',
  },
  {
    kind: 'world-model',
    name: 'Robotics foundation models',
    provider: 'Multiple labs',
    status: 'preview',
    pricing: 'Platform / enterprise access',
    unit: 'API, compute, license',
    capabilities: ['robotics', 'policy learning', 'simulation'],
    bestFor: 'Enterprise robotics and embodied AI evaluation.',
  },
];

export function catalogForKind(kind: AiCatalogKind): AiCatalogItem[] {
  return AI_VERTICAL_CATALOG.filter((item) => item.kind === kind);
}
