import { ImageResponse } from 'next/og';
import { ogTemplate, OG_SIZE, OG_CONTENT_TYPE } from '@/lib/og-template';
import { sql } from '@/lib/db';

export const alt = 'Model API Pricing — aiplans.dev';
export const size = OG_SIZE;
export const contentType = OG_CONTENT_TYPE;

// Fetches real data per model so shared Twitter/WeChat cards show the
// actual model name + price range + Arena ELO instead of a generic logo.
export default async function Image({
  params,
}: {
  params: Promise<{ locale: string; slug: string }>;
}) {
  const { locale, slug } = await params;
  const isZh = locale === 'zh';

  // Fetch model + channels + arena elo. These are small queries and the
  // The result is generated by Next.js and can be cached by the reverse proxy
  // or CDN because this route is static-ish (not user-specific).
  const [model] = await sql<any[]>`
    SELECT id, name, slug, context_window
    FROM models
    WHERE slug = ${slug}
    LIMIT 1
  `;

  if (!model) {
    // Fall back to a generic OG if model wasn't found — still better
    // than a broken image URL.
    return new ImageResponse(
      ogTemplate({
        kicker: isZh ? 'API 价格' : 'API Pricing',
        title: slug,
        subtitle: isZh ? '模型未找到' : 'Model not found',
        locale: isZh ? 'zh' : 'en',
      }),
      size,
    );
  }

  // Compute min USD price across the model's channels
  const [modelChannels, arena] = await Promise.all([
    sql<any[]>`
      SELECT input_price_per_1m, currency
      FROM api_channel_prices
      WHERE model_id = ${model.id} AND is_available = true
    `,
    sql<any[]>`
      SELECT s.value
      FROM model_benchmark_scores s
      JOIN benchmark_metrics bm ON bm.id = s.metric_id
      WHERE s.model_id = ${model.id} AND bm.name = 'ELO'
      ORDER BY s.value DESC NULLS LAST
      LIMIT 1
    `,
  ]);
  const usdPrices = modelChannels
    .filter((c: any) => (c.currency ?? 'USD') === 'USD' && typeof c.input_price_per_1m === 'number' && c.input_price_per_1m > 0)
    .map((c: any) => c.input_price_per_1m as number)
    .sort((a: number, b: number) => a - b);
  const lowest = usdPrices[0];
  const channelCount = modelChannels.length;

  const eloRow = arena[0];
  const elo = eloRow?.value as number | undefined;

  const stats: { label: string; value: string }[] = [];
  if (channelCount > 0) {
    stats.push({ label: isZh ? '渠道' : 'Channels', value: String(channelCount) });
  }
  if (lowest != null) {
    stats.push({
      label: isZh ? '最低 / 1M' : 'From / 1M',
      value: `$${lowest < 1 ? lowest.toFixed(2) : lowest.toFixed(1)}`,
    });
  }
  if (elo != null) {
    stats.push({ label: isZh ? 'Arena ELO' : 'Arena ELO', value: String(Math.round(elo)) });
  }

  const subtitle = isZh
    ? `${model.context_window?.toLocaleString() ?? '?'} token 上下文 · ${channelCount} 个渠道价格对比`
    : `${model.context_window?.toLocaleString() ?? '?'} token context · ${channelCount} channels compared`;

  return new ImageResponse(
    ogTemplate({
      kicker: isZh ? 'API 价格' : 'API Pricing',
      title: model.name,
      subtitle,
      stats,
      locale: isZh ? 'zh' : 'en',
    }),
    size,
  );
}
